version: "3.8"

services:
  app:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - mongodb

  mongodb:
    image: mongo:7
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    # Sem volume, para teste

# para subir rebuildando app e resetando banco:
# docker compose -f docker-compose.test.yml down -v && docker compose -f docker-compose.test.yml up --build
# para parar: docker compose -f docker-compose.test.yml down